#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-level-folder>" 1>&2
    exit 1
fi

top="$1"
if test ! -d "$top"; then
    echo "Error: Argument $top is not a folder." 1>&2
    exit 1
fi

create_substructure()
{
    mkdir "$1"
    mkdir "$1"/raw
    mkdir "$1"/common
    mkdir "$1"/entire
    mkdir "$1"/per-semester
    mkdir "$1"/per-series
}

create_substructure "$top"/json
create_substructure "$top"/csv
create_substructure "$top"/processed
create_substructure "$top"/xls
create_substructure "$top"/xlsx
create_substructure "$top"/processed-xls
create_substructure "$top"/processed-xlsx

mkdir "$top"/sep
create_substructure "$top"/sep/cti
create_substructure "$top"/sep/is

mkdir "$top"/sep-json
create_substructure "$top"/sep-json/cti
create_substructure "$top"/sep-json/is

mkdir "$top"/sep-csv
create_substructure "$top"/sep-csv/cti
create_substructure "$top"/sep-csv/is

mkdir "$top"/sep-processed
create_substructure "$top"/sep-processed/cti
create_substructure "$top"/sep-processed/is
mkdir "$top"/sep-processed/cti/average
mkdir "$top"/sep-processed/is/average

mkdir "$top"/sep-xls
mkdir "$top"/sep-xlsx
create_substructure "$top"/sep-xls/cti
create_substructure "$top"/sep-xls/is
create_substructure "$top"/sep-xlsx/cti
create_substructure "$top"/sep-xlsx/is

create_substructure "$top"/user-json

mkdir "$top"/sep-processed-xlsx
create_substructure "$top"/sep-processed-xlsx/cti
create_substructure "$top"/sep-processed-xlsx/is
mkdir "$top"/sep-processed-xlsx/cti/average
mkdir "$top"/sep-processed-xlsx/is/average

mkdir "$top"/user
mkdir "$top"/user/json

mkdir "$top"/summary
mkdir "$top"/summary/cti
mkdir "$top"/summary/is

mkdir "$top"/summary-xlsx
mkdir "$top"/summary-xlsx/cti
mkdir "$top"/summary-xlsx/is

mkdir "$top"/summary-xlsx
mkdir "$top"/summary-xlsx/cti
mkdir "$top"/summary-xlsx/is

mkdir "$top"/mapping/
mkdir "$top"/mapping/num_feedbacks
mkdir "$top"/mapping/cti
mkdir "$top"/mapping/cti/num_feedbacks
mkdir "$top"/mapping/num_users
mkdir "$top"/mapping/is
mkdir "$top"/mapping/is/num_feedbacks

mkdir "$top"/analysis
mkdir "$top"/analysis/cti
mkdir "$top"/analysis/is

mkdir "$top"/analysis-xls
mkdir "$top"/analysis-xls/cti
mkdir "$top"/analysis-xls/is

mkdir "$top"/analysis-xlsx
mkdir "$top"/analysis-xlsx/cti
mkdir "$top"/analysis-xlsx/is
