#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./json2csv-folder "$top"/json/raw "$top"/csv/raw
./remove_extra "$top"/csv/raw
find "$top"/csv/raw -size 0 -delete

for i in 01-ELECTRO 02-ENERG 03-ACS 04-ELECTRONICA 05-FIMM 06-FIIR 07-ISB 08-Transp 09-AERO 10-SIM 11-CHIM 12-FILS 13-FSA 14-FIM 15-FAIMA 16-DPPD; do
    ./json2csv-folder "$top"/"$i"/json/raw "$top"/"$i"/csv/raw
    ./remove_extra "$top"/"$i"/csv/raw
    find "$top"/"$i"/csv/raw -size 0 -delete
done
