#!/bin/bash

if test $# -ne 2; then
    echo "Usage: $0 <csv-folder> <xlsx-folder>" 1>&2
    exit 1
fi

if ! command -v ssconvert > /dev/null 2>&1; then
    echo 'ssconvert missing (search for the "gnumeric" package)' 1>&2
    exit 1
fi

IFS=$'\n'
for f in "$1"/*.csv; do
    xlsx="$2"/"$(basename "$f" .csv).xlsx"
    echo "Convert $f to $xlsx"
    ssconvert "$f" "$xlsx" > /dev/null 2>&1
done
