#!/bin/bash

if test $# -ne 2; then
    echo "Usage: $0 <csv-unprocessed-folder> <csv-processed-folder>" 1>&2
    exit 1
fi

in="$1"
out="$2"

for i in "$in"/*.csv; do
    echo "Processing $i ..."
    full_in_path="$(cd "$(dirname "$i")"; pwd)/$(basename "$i")"
    full_out_path="$(cd "$(dirname "$out")"; pwd)/$(basename "$out")"
    pushd .. > /dev/null
    ./process_feedback.py < "$full_in_path" > "$full_out_path"/"$(basename "$full_in_path")"
    popd > /dev/null
done
