#!/bin/bash

if test $# -ne 2; then
    echo "Usage: $0 <folder with .json files> <output-separted-folder>" 1>&2
    exit 1
fi

in="$1"
out="$2"

if test ! -d "$in"; then
    echo "Error: Folder $in does not exist or is not a folder." 1>&2
    exit 1
fi

if test ! -d "$out"; then
    echo "Error: Argument $out (output) is not a folder." 1>&2
    exit 1
fi

IFS=$'\n'
for i in "$in"/*.json; do
    num=$(cat "$i" | jq -r '.[] | [.roles[0].shortname] | @csv' | grep '"student"$' | wc -l)
    echo "\"$(basename "$i" .json)\",\"$num\""
done > "$out"/num_users.csv
