#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./summarize_per_series.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/per_series.csv
./summarize_per_semester.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/per_semester.csv
./summarize_common.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/common.csv
./summarize_prof.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/prof.csv

for f in 01-ELECTRO 02-ENERG 03-ACS 04-ELECTRONICA 05-FIMM 06-FIIR 07-ISB 08-Transp 09-AERO 10-SIM 11-CHIM 12-FILS 13-FSA 14-FIM 15-FAIMA 16-DPPD; do
    ./summarize_per_series.py "$top"/"$f"/mapping/num_feedbacks/raw.csv > "$top"/"$f"/mapping/num_feedbacks/per_series.csv
    ./summarize_per_semester.py "$top"/"$f"/mapping/num_feedbacks/raw.csv > "$top"/"$f"/mapping/num_feedbacks/per_semester.csv
    ./summarize_common.py "$top"/"$f"/mapping/num_feedbacks/raw.csv > "$top"/"$f"/mapping/num_feedbacks/common.csv
    ./summarize_prof.py "$top"/"$f"/mapping/num_feedbacks/raw.csv > "$top"/"$f"/mapping/num_feedbacks/prof.csv
done
