#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./json2csv-folder "$top"/json/raw "$top"/csv/raw
./json2csv-folder "$top"/sep-json/is/raw "$top"/sep-csv/is/raw
./json2csv-folder "$top"/sep-json/cti/raw "$top"/sep-csv/cti/raw
./remove_extra "$top"/csv/raw
./remove_extra "$top"/sep-csv/is/raw
./remove_extra "$top"/sep-csv/cti/raw
