#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

#./separate_acs "$top"/csv/raw/ "$top"/sep/

./make_entire "$top"/csv/raw/ "$top"/csv/entire/
./make_entire "$top"/sep-csv/cti/raw/ "$top"/sep-csv/cti/entire/
./make_entire "$top"/sep-csv/is/raw/ "$top"/sep-csv/is/entire/

./make_common "$top"/csv/raw/ "$top"/csv/common/
./make_common "$top"/sep-csv/cti/raw/ "$top"/sep-csv/cti/common/
./make_common "$top"/sep-csv/is/raw/ "$top"/sep-csv/is/common/

./make_per_series "$top"/csv/raw/ "$top"/csv/per-series/
./make_per_series "$top"/sep-csv/cti/raw/ "$top"/sep-csv/cti/per-series/
./make_per_series "$top"/sep-csv/is/raw/ "$top"/sep-csv/is/per-series/

./make_per_semester "$top"/csv/raw/ "$top"/csv/per-semester/
./make_per_semester "$top"/sep-csv/cti/raw/ "$top"/sep-csv/cti/per-semester/
./make_per_semester "$top"/sep-csv/is/raw/ "$top"/sep-csv/is/per-semester/

./process_folder "$top"/csv/raw/ "$top"/processed/raw/
./process_folder "$top"/csv/entire/ "$top"/processed/entire/
./process_folder "$top"/csv/common/ "$top"/processed/common/
./process_folder "$top"/csv/per-series/ "$top"/processed/per-series/
./process_folder "$top"/csv/per-semester/ "$top"/processed/per-semester/

./process_folder "$top"/sep-csv/cti/raw/ "$top"/sep-processed/cti/raw/
./process_folder "$top"/sep-csv/cti/entire/ "$top"/sep-processed/cti/entire/
./process_folder "$top"/sep-csv/cti/common/ "$top"/sep-processed/cti/common/
./process_folder "$top"/sep-csv/cti/per-series/ "$top"/sep-processed/cti/per-series/
./process_folder "$top"/sep-csv/cti/per-semester/ "$top"/sep-processed/cti/per-semester/

./process_folder "$top"/sep-csv/is/raw/ "$top"/sep-processed/is/raw/
./process_folder "$top"/sep-csv/is/entire/ "$top"/sep-processed/is/entire/
./process_folder "$top"/sep-csv/is/common/ "$top"/sep-processed/is/common/
./process_folder "$top"/sep-csv/is/per-series/ "$top"/sep-processed/is/per-series/
./process_folder "$top"/sep-csv/is/per-semester/ "$top"/sep-processed/is/per-semester/

./append_average "$top"/sep-processed/cti/
./append_average "$top"/sep-processed/is/

./csv2xlsx "$top"/csv/raw/ "$top"/xlsx/raw/
./csv2xlsx "$top"/csv/entire/ "$top"/xlsx/entire/
./csv2xlsx "$top"/csv/common/ "$top"/xlsx/common/
./csv2xlsx "$top"/csv/per-series/ "$top"/xlsx/per-series/
./csv2xlsx "$top"/csv/per-semester/ "$top"/xlsx/per-semester/

./csv2xlsx "$top"/processed/raw/ "$top"/processed-xlsx/raw/
./csv2xlsx "$top"/processed/entire/ "$top"/processed-xlsx/entire/
./csv2xlsx "$top"/processed/common/ "$top"/processed-xlsx/common/
./csv2xlsx "$top"/processed/per-series/ "$top"/processed-xlsx/per-series/
./csv2xlsx "$top"/processed/per-semester/ "$top"/processed-xlsx/per-semester/

./csv2xlsx "$top"/sep/cti/raw/ "$top"/sep-xlsx/cti/raw/
./csv2xlsx "$top"/sep/cti/entire/ "$top"/sep-xlsx/cti/entire/
./csv2xlsx "$top"/sep/cti/common/ "$top"/sep-xlsx/cti/common/
./csv2xlsx "$top"/sep/cti/per-series/ "$top"/sep-xlsx/cti/per-series/
./csv2xlsx "$top"/sep/cti/per-semester/ "$top"/sep-xlsx/cti/per-semester/

./csv2xlsx "$top"/sep/is/raw/ "$top"/sep-xlsx/is/raw/
./csv2xlsx "$top"/sep/is/entire/ "$top"/sep-xlsx/is/entire/
./csv2xlsx "$top"/sep/is/common/ "$top"/sep-xlsx/is/common/
./csv2xlsx "$top"/sep/is/per-series/ "$top"/sep-xlsx/is/per-series/
./csv2xlsx "$top"/sep/is/per-semester/ "$top"/sep-xlsx/is/per-semester/

./csv2xlsx "$top"/sep-processed/cti/raw/ "$top"/sep-processed-xlsx/cti/raw/
./csv2xlsx "$top"/sep-processed/cti/entire/ "$top"/sep-processed-xlsx/cti/entire/
./csv2xlsx "$top"/sep-processed/cti/common/ "$top"/sep-processed-xlsx/cti/common/
./csv2xlsx "$top"/sep-processed/cti/per-series/ "$top"/sep-processed-xlsx/cti/per-series/
./csv2xlsx "$top"/sep-processed/cti/per-semester/ "$top"/sep-processed-xlsx/cti/per-semester/
./csv2xlsx "$top"/sep-processed/cti/average/ "$top"/sep-processed-xlsx/cti/average/

./csv2xlsx "$top"/sep-processed/is/raw/ "$top"/sep-processed-xlsx/is/raw/
./csv2xlsx "$top"/sep-processed/is/entire/ "$top"/sep-processed-xlsx/is/entire/
./csv2xlsx "$top"/sep-processed/is/common/ "$top"/sep-processed-xlsx/is/common/
./csv2xlsx "$top"/sep-processed/is/per-series/ "$top"/sep-processed-xlsx/is/per-series/
./csv2xlsx "$top"/sep-processed/is/average/ "$top"/sep-processed-xlsx/is/average/
